### ISSUE TITLE
OSSClient无法注入

### ISSUE THREAD

**Issue by prettydva** [aliyun/aliyun-oss-java-sdk#342]
**springcloud版本：Greenwich.SR3**    ，  **springcloud-alibaba版本：2.1.0.RELEASE**

配置文件：
```
server:
  port: 8086
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    alicloud:
      access-key: 我的access-key
      secret-key: 我的secret-key
      oss:
        endpoint: oss-cn-hangzhou.aliyuncs.com
```

错误信息：
```
Description:

Field ossClient in com.black.gmall.service.impl.OssServiceImpl required a bean of type 'com.aliyun.oss.OSSClient' that could not be found.

The injection point has the following annotations:
	- @org.springframework.beans.factory.annotation.Autowired(required=true)


Action:

Consider defining a bean of type 'com.aliyun.oss.OSSClient' in your configuration.

```
